# Generated by Django 6.1 on 2026-08-12 10:31

import django.core.validators
import transfers.models
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(default=transfers.models.generate_reference, editable=False, max_length=16, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('currency', models.CharField(choices=[('NGN', 'Nigerian Naira'), ('GBP', 'Pound Sterling'), ('USD', 'US Dollar')], max_length=3)),
                ('recipient_ref', models.CharField(max_length=128)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=16)),
                ('provider_transfer_id', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('idempotency_key', models.CharField(max_length=128, unique=True)),
                ('request_fingerprint', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
