# Generated by Django 6.1 on 2026-08-12 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfers', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='transfer',
            constraint=models.CheckConstraint(condition=models.Q(('provider_transfer_id', ''), _negated=True), name='provider_transfer_id_is_null_or_non_empty'),
        ),
    ]
