# Generated by Django 6.1 on 2026-08-12 10:56

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfers', '0002_transfer_provider_transfer_id_is_null_or_non_empty'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='transfer',
            index=models.Index(fields=['-created_at', '-id'], name='transfer_newest_first'),
        ),
        migrations.AddConstraint(
            model_name='transfer',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gte', Decimal('0.01'))), name='amount_at_least_one_minor_unit'),
        ),
    ]
