# Generated by Django 6.1 on 2026-08-12 11:12

import transfers.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfers', '0003_transfer_transfer_newest_first_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfer',
            name='reference',
            field=models.CharField(default=transfers.models.generate_reference, editable=False, max_length=20, unique=True),
        ),
    ]
