# Generated by Django 6.1 on 2026-08-12 11:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfers', '0004_alter_transfer_reference'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(max_length=128, unique=True)),
                ('provider_transfer_id', models.CharField(db_index=True, max_length=64)),
                ('payload', models.JSONField()),
                ('outcome', models.CharField(choices=[('received', 'Received, not yet judged'), ('applied', 'Applied'), ('rejected_illegal_transition', 'Rejected: illegal transition'), ('rejected_unknown_transfer', 'Rejected: unknown transfer')], default='received', max_length=32)),
                ('occurred_at', models.DateTimeField(blank=True, null=True)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('transfer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='webhook_events', to='transfers.transfer')),
            ],
            options={
                'ordering': ['-received_at', '-id'],
            },
        ),
    ]
